import type { ModuleSpec } from './types';

/**
 * Registry modul operasional Tenant Web.
 *
 * Sumber struktur: `.menu/seeded-navigation.md` (Sidebar Tenant).
 * Data masih **mock** (TDD UI, rules.md §4) karena endpoint tenant untuk modul
 * operasional masih dikerjakan. Kolom sudah disusun mengikuti bentuk data yang
 * diharapkan, jadi saat API siap cukup menukar sumber datanya.
 */
export const MODULES: ModuleSpec[] = [
  // ── Customer ───────────────────────────────────────────────────────────────
  {
    path: '/customers',
    title: 'Customers',
    description: 'Data pelanggan showroom beserta kontak dan aktivitasnya.',
    icon: 'contact',
    resource: 'customer.customer',
    createLabel: 'Tambah Customer',
    columns: [
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'name', header: 'Nama', kind: 'bold' },
      { key: 'phone', header: 'Telepon' },
      { key: 'city', header: 'Kota' },
      { key: 'type', header: 'Tipe' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'c1', code: 'CUS-0001', name: 'Budi Santoso', phone: '0812-1111-2222', city: 'Bandung', type: 'Individu', status: 'ACTIVE' },
      { id: 'c2', code: 'CUS-0002', name: 'PT Maju Jaya', phone: '022-555-8899', city: 'Bandung', type: 'Perusahaan', status: 'ACTIVE' },
      { id: 'c3', code: 'CUS-0003', name: 'Siti Rahma', phone: '0813-4444-5555', city: 'Cimahi', type: 'Individu', status: 'INACTIVE' },
    ],
  },

  // ── Catalogue ──────────────────────────────────────────────────────────────
  {
    path: '/catalogue/products',
    title: 'Products',
    description: 'Master produk dan varian kendaraan.',
    icon: 'product',
    resource: 'catalogue.product',
    createLabel: 'Tambah Produk',
    columns: [
      { key: 'sku', header: 'SKU', kind: 'mono' },
      { key: 'name', header: 'Nama Produk', kind: 'bold' },
      { key: 'brand', header: 'Merek' },
      { key: 'category', header: 'Kategori' },
      { key: 'price', header: 'Harga', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'p1', sku: 'AVZ-15-G', name: 'Toyota Avanza 1.5 G', brand: 'Toyota', category: 'MPV', price: 245000000, status: 'ACTIVE' },
      { id: 'p2', sku: 'XPD-15-U', name: 'Mitsubishi Xpander Ultimate', brand: 'Mitsubishi', category: 'MPV', price: 285000000, status: 'ACTIVE' },
      { id: 'p3', sku: 'BRV-15-E', name: 'Honda BR-V E CVT', brand: 'Honda', category: 'SUV', price: 315000000, status: 'INACTIVE' },
    ],
  },
  {
    path: '/catalogue/categories',
    title: 'Categories',
    description: 'Kategori produk katalog.',
    icon: 'category',
    resource: 'catalogue.category',
    createLabel: 'Tambah Kategori',
    columns: [
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'name', header: 'Kategori', kind: 'bold' },
      { key: 'products', header: 'Jumlah Produk', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'cat1', code: 'MPV', name: 'MPV', products: 12, status: 'ACTIVE' },
      { id: 'cat2', code: 'SUV', name: 'SUV', products: 8, status: 'ACTIVE' },
      { id: 'cat3', code: 'SEDAN', name: 'Sedan', products: 3, status: 'ACTIVE' },
    ],
  },
  {
    path: '/catalogue/brands',
    title: 'Brands',
    description: 'Merek kendaraan yang dijual.',
    icon: 'brand',
    resource: 'catalogue.brand',
    createLabel: 'Tambah Merek',
    columns: [
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'name', header: 'Merek', kind: 'bold' },
      { key: 'country', header: 'Negara' },
      { key: 'products', header: 'Produk', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'b1', code: 'TOY', name: 'Toyota', country: 'Jepang', products: 9, status: 'ACTIVE' },
      { id: 'b2', code: 'HON', name: 'Honda', country: 'Jepang', products: 6, status: 'ACTIVE' },
      { id: 'b3', code: 'MIT', name: 'Mitsubishi', country: 'Jepang', products: 5, status: 'ACTIVE' },
    ],
  },
  {
    path: '/catalogue/price-lists',
    title: 'Price Lists',
    description: 'Daftar harga per periode dan segmen.',
    icon: 'pricelist',
    resource: 'catalogue.price_list',
    createLabel: 'Tambah Price List',
    columns: [
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'name', header: 'Nama', kind: 'bold' },
      { key: 'validFrom', header: 'Berlaku Dari', kind: 'date' },
      { key: 'validTo', header: 'Sampai', kind: 'date' },
      { key: 'items', header: 'Item', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'pl1', code: 'PL-2026-Q3', name: 'Harga Retail Q3 2026', validFrom: '2026-07-01', validTo: '2026-09-30', items: 24, status: 'ACTIVE' },
      { id: 'pl2', code: 'PL-2026-Q2', name: 'Harga Retail Q2 2026', validFrom: '2026-04-01', validTo: '2026-06-30', items: 22, status: 'INACTIVE' },
    ],
  },

  // ── Inventory ──────────────────────────────────────────────────────────────
  {
    path: '/inventory/stocks',
    title: 'Stock',
    description: 'Posisi stok per item dan lokasi.',
    icon: 'stock',
    resource: 'inventory.stock',
    columns: [
      { key: 'sku', header: 'SKU', kind: 'mono' },
      { key: 'name', header: 'Item', kind: 'bold' },
      { key: 'location', header: 'Lokasi' },
      { key: 'onHand', header: 'On Hand', kind: 'number', align: 'center' },
      { key: 'reserved', header: 'Reserved', kind: 'number', align: 'center' },
      { key: 'available', header: 'Available', kind: 'number', align: 'center' },
    ],
    rows: [
      { id: 's1', sku: 'AVZ-15-G', name: 'Toyota Avanza 1.5 G', location: 'Gudang Pusat', onHand: 6, reserved: 2, available: 4 },
      { id: 's2', sku: 'XPD-15-U', name: 'Mitsubishi Xpander Ultimate', location: 'Showroom', onHand: 3, reserved: 1, available: 2 },
      { id: 's3', sku: 'BRV-15-E', name: 'Honda BR-V E CVT', location: 'Gudang Pusat', onHand: 0, reserved: 0, available: 0 },
    ],
  },
  {
    path: '/inventory/serialized-stocks',
    title: 'Serialized Stock',
    description: 'Stok kendaraan per unit (VIN / nomor rangka).',
    icon: 'vehicle',
    resource: 'inventory.serialized_stock',
    columns: [
      { key: 'vin', header: 'VIN', kind: 'mono' },
      { key: 'product', header: 'Produk', kind: 'bold' },
      { key: 'color', header: 'Warna' },
      { key: 'location', header: 'Lokasi' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ss1', vin: 'MHKM1BA3JKJ001122', product: 'Toyota Avanza 1.5 G', color: 'Putih', location: 'Showroom', status: 'ACTIVE' },
      { id: 'ss2', vin: 'MHKM1BA3JKJ003344', product: 'Mitsubishi Xpander Ultimate', color: 'Hitam', location: 'Gudang Pusat', status: 'RESERVED' },
      { id: 'ss3', vin: 'MHKM1BA3JKJ005566', product: 'Honda BR-V E CVT', color: 'Silver', location: 'Showroom', status: 'SOLD' },
    ],
  },
  {
    path: '/inventory/locations',
    title: 'Locations',
    description: 'Lokasi penyimpanan stok.',
    icon: 'location',
    resource: 'inventory.location',
    createLabel: 'Tambah Lokasi',
    columns: [
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'name', header: 'Lokasi', kind: 'bold' },
      { key: 'type', header: 'Tipe' },
      { key: 'address', header: 'Alamat', kind: 'muted' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'l1', code: 'WH-01', name: 'Gudang Pusat', type: 'Gudang', address: 'Jl. Soekarno Hatta 12', status: 'ACTIVE' },
      { id: 'l2', code: 'SR-01', name: 'Showroom Utama', type: 'Showroom', address: 'Jl. Asia Afrika 88', status: 'ACTIVE' },
    ],
  },
  {
    path: '/inventory/movements',
    title: 'Movements',
    description: 'Riwayat pergerakan stok masuk dan keluar.',
    icon: 'movement',
    resource: 'inventory.movement',
    columns: [
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'ref', header: 'Referensi', kind: 'mono' },
      { key: 'item', header: 'Item', kind: 'bold' },
      { key: 'type', header: 'Tipe' },
      { key: 'qty', header: 'Qty', kind: 'number', align: 'center' },
      { key: 'location', header: 'Lokasi' },
    ],
    rows: [
      { id: 'mv1', date: '2026-07-10', ref: 'GR-0012', item: 'Toyota Avanza 1.5 G', type: 'Masuk', qty: 3, location: 'Gudang Pusat' },
      { id: 'mv2', date: '2026-07-11', ref: 'SO-0031', item: 'Honda BR-V E CVT', type: 'Keluar', qty: 1, location: 'Showroom' },
    ],
  },
  {
    path: '/inventory/transfers',
    title: 'Transfers',
    description: 'Perpindahan stok antar lokasi.',
    icon: 'transfer',
    resource: 'inventory.transfer',
    createLabel: 'Buat Transfer',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'from', header: 'Dari' },
      { key: 'to', header: 'Ke' },
      { key: 'items', header: 'Item', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'tr1', number: 'TRF-0007', date: '2026-07-09', from: 'Gudang Pusat', to: 'Showroom Utama', items: 2, status: 'ACTIVE' },
      { id: 'tr2', number: 'TRF-0006', date: '2026-07-02', from: 'Showroom Utama', to: 'Gudang Pusat', items: 1, status: 'PENDING' },
    ],
  },
  {
    path: '/inventory/adjustments',
    title: 'Adjustments',
    description: 'Penyesuaian stok hasil opname atau koreksi.',
    icon: 'adjustment',
    resource: 'inventory.adjustment',
    createLabel: 'Buat Adjustment',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'reason', header: 'Alasan' },
      { key: 'items', header: 'Item', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ad1', number: 'ADJ-0003', date: '2026-07-08', reason: 'Selisih opname', items: 1, status: 'PENDING' },
    ],
  },

  {
    path: '/inventory/stock-counts',
    title: 'Stock Counts',
    description: 'Opname stok dan hasil perhitungannya.',
    icon: 'stockcount',
    resource: 'inventory.stock_count',
    createLabel: 'Buat Stock Count',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'location', header: 'Lokasi' },
      { key: 'items', header: 'Item', kind: 'number', align: 'center' },
      { key: 'variance', header: 'Selisih', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'sc1', number: 'SC-0002', date: '2026-07-05', location: 'Gudang Pusat', items: 12, variance: 1, status: 'PENDING' },
    ],
  },
  {
    path: '/inventory/reports',
    title: 'Inventory Reports',
    description: 'Laporan stok, mutasi, dan umur persediaan.',
    icon: 'report',
    resource: 'inventory.report',
    columns: [
      { key: 'name', header: 'Laporan', kind: 'bold' },
      { key: 'period', header: 'Periode' },
      { key: 'updatedAt', header: 'Diperbarui', kind: 'date' },
    ],
    rows: [
      { id: 'ir1', name: 'Stock on Hand', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'ir2', name: 'Stock Movement', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'ir3', name: 'Stock Aging', period: 'Juli 2026', updatedAt: '2026-07-12' },
    ],
  },

  // ── Purchasing ─────────────────────────────────────────────────────────────
  {
    path: '/purchasing/suppliers',
    title: 'Suppliers',
    description: 'Data pemasok kendaraan dan sparepart.',
    icon: 'supplier',
    resource: 'purchasing.supplier',
    createLabel: 'Tambah Supplier',
    columns: [
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'name', header: 'Supplier', kind: 'bold' },
      { key: 'phone', header: 'Telepon' },
      { key: 'city', header: 'Kota' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'sp1', code: 'SUP-001', name: 'PT Astra Distribusi', phone: '021-555-1234', city: 'Jakarta', status: 'ACTIVE' },
      { id: 'sp2', code: 'SUP-002', name: 'CV Sumber Mobil', phone: '022-777-8888', city: 'Bandung', status: 'ACTIVE' },
    ],
  },
  {
    path: '/purchasing/purchase-requests',
    title: 'Purchase Requests',
    description: 'Permintaan pembelian sebelum menjadi PO.',
    icon: 'purchaserequest',
    resource: 'purchasing.purchase_request',
    createLabel: 'Buat PR',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'requester', header: 'Pemohon' },
      { key: 'items', header: 'Item', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'pr1', number: 'PR-0021', date: '2026-07-05', requester: 'Andi', items: 3, status: 'PENDING' },
      { id: 'pr2', number: 'PR-0020', date: '2026-07-01', requester: 'Rina', items: 1, status: 'ACTIVE' },
    ],
  },
  {
    path: '/purchasing/purchase-orders',
    title: 'Purchase Orders',
    description: 'Pesanan pembelian ke supplier.',
    icon: 'purchaseorder',
    resource: 'purchasing.purchase_order',
    createLabel: 'Buat PO',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'supplier', header: 'Supplier', kind: 'bold' },
      { key: 'total', header: 'Total', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'po1', number: 'PO-0044', date: '2026-07-06', supplier: 'PT Astra Distribusi', total: 735000000, status: 'ACTIVE' },
      { id: 'po2', number: 'PO-0043', date: '2026-06-28', supplier: 'CV Sumber Mobil', total: 285000000, status: 'PENDING' },
    ],
  },
  {
    path: '/purchasing/goods-receipts',
    title: 'Goods Receipts',
    description: 'Penerimaan barang dari purchase order.',
    icon: 'goodsreceipt',
    resource: 'purchasing.goods_receipt',
    createLabel: 'Buat Penerimaan',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'po', header: 'PO', kind: 'mono' },
      { key: 'items', header: 'Item', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'gr1', number: 'GR-0012', date: '2026-07-10', po: 'PO-0044', items: 3, status: 'ACTIVE' },
    ],
  },
  {
    path: '/purchasing/purchase-invoices',
    title: 'Purchase Invoices',
    description: 'Faktur pembelian dari supplier.',
    icon: 'invoice',
    resource: 'purchasing.purchase_invoice',
    createLabel: 'Buat Faktur',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'supplier', header: 'Supplier', kind: 'bold' },
      { key: 'total', header: 'Total', kind: 'money', align: 'right' },
      { key: 'dueDate', header: 'Jatuh Tempo', kind: 'date' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'pi1', number: 'PINV-0031', date: '2026-07-10', supplier: 'PT Astra Distribusi', total: 735000000, dueDate: '2026-08-09', status: 'PENDING' },
    ],
  },
  {
    path: '/purchasing/purchase-returns',
    title: 'Purchase Returns',
    description: 'Retur barang ke supplier.',
    icon: 'return',
    resource: 'purchasing.purchase_return',
    createLabel: 'Buat Retur',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'supplier', header: 'Supplier', kind: 'bold' },
      { key: 'reason', header: 'Alasan' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'prt1', number: 'PRT-0002', date: '2026-06-30', supplier: 'CV Sumber Mobil', reason: 'Unit cacat', status: 'PENDING' },
    ],
  },

  {
    path: '/purchasing/reports',
    title: 'Purchasing Reports',
    description: 'Laporan pembelian per supplier dan periode.',
    icon: 'report',
    resource: 'purchasing.report',
    columns: [
      { key: 'name', header: 'Laporan', kind: 'bold' },
      { key: 'period', header: 'Periode' },
      { key: 'updatedAt', header: 'Diperbarui', kind: 'date' },
    ],
    rows: [
      { id: 'pur1', name: 'Purchase by Supplier', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'pur2', name: 'Outstanding PO', period: 'Juli 2026', updatedAt: '2026-07-12' },
    ],
  },

  // ── Sales ──────────────────────────────────────────────────────────────────
  {
    path: '/sales/leads',
    title: 'Leads',
    description: 'Calon pembeli dan tahap follow-up-nya.',
    icon: 'lead',
    resource: 'sales.lead',
    createLabel: 'Tambah Lead',
    columns: [
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'name', header: 'Nama', kind: 'bold' },
      { key: 'phone', header: 'Telepon' },
      { key: 'interest', header: 'Minat' },
      { key: 'source', header: 'Sumber' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ld1', code: 'LEAD-0101', name: 'Dedi Kurniawan', phone: '0811-2222-3333', interest: 'Toyota Avanza', source: 'Walk-in', status: 'ACTIVE' },
      { id: 'ld2', code: 'LEAD-0102', name: 'Maya Putri', phone: '0812-9999-8888', interest: 'Honda BR-V', source: 'Instagram', status: 'PENDING' },
    ],
  },
  {
    path: '/sales/quotations',
    title: 'Quotations',
    description: 'Penawaran harga ke calon pembeli.',
    icon: 'quotation',
    resource: 'sales.quotation',
    createLabel: 'Buat Penawaran',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'total', header: 'Total', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'q1', number: 'QUO-0018', date: '2026-07-09', customer: 'Dedi Kurniawan', total: 245000000, status: 'PENDING' },
    ],
  },
  {
    path: '/sales/orders',
    title: 'Sales Orders',
    description: 'Pesanan penjualan kendaraan.',
    icon: 'order',
    resource: 'sales.order',
    createLabel: 'Buat Sales Order',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'product', header: 'Unit' },
      { key: 'total', header: 'Total', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'so1', number: 'SO-0031', date: '2026-07-11', customer: 'Budi Santoso', product: 'Honda BR-V E CVT', total: 315000000, status: 'ACTIVE' },
      { id: 'so2', number: 'SO-0030', date: '2026-07-04', customer: 'PT Maju Jaya', product: 'Toyota Avanza 1.5 G', total: 245000000, status: 'PENDING' },
    ],
  },
  {
    path: '/sales/invoices',
    title: 'Sales Invoices',
    description: 'Faktur penjualan dan status pembayarannya.',
    icon: 'invoice',
    resource: 'sales.invoice',
    createLabel: 'Buat Faktur',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'total', header: 'Total', kind: 'money', align: 'right' },
      { key: 'dueDate', header: 'Jatuh Tempo', kind: 'date' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'si1', number: 'INV-0027', date: '2026-07-11', customer: 'Budi Santoso', total: 315000000, dueDate: '2026-07-25', status: 'PENDING' },
    ],
  },
  {
    path: '/sales/returns',
    title: 'Sales Returns',
    description: 'Retur penjualan dari pelanggan.',
    icon: 'return',
    resource: 'sales.return',
    createLabel: 'Buat Retur',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'reason', header: 'Alasan' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [],
  },

  {
    path: '/sales/reports',
    title: 'Sales Reports',
    description: 'Laporan penjualan, funnel, dan performa sales.',
    icon: 'report',
    resource: 'sales.report',
    columns: [
      { key: 'name', header: 'Laporan', kind: 'bold' },
      { key: 'period', header: 'Periode' },
      { key: 'updatedAt', header: 'Diperbarui', kind: 'date' },
    ],
    rows: [
      { id: 'sr1', name: 'Sales by Product', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'sr2', name: 'Lead Conversion', period: 'Juli 2026', updatedAt: '2026-07-12' },
    ],
  },

  // ── Showroom ───────────────────────────────────────────────────────────────
  {
    path: '/showroom/vehicle-units',
    title: 'Vehicle Units',
    description: 'Unit kendaraan fisik beserta kondisi dan dokumennya.',
    icon: 'vehicle',
    resource: 'showroom.vehicle_unit',
    createLabel: 'Tambah Unit',
    columns: [
      { key: 'vin', header: 'VIN', kind: 'mono' },
      { key: 'product', header: 'Produk', kind: 'bold' },
      { key: 'year', header: 'Tahun', align: 'center' },
      { key: 'color', header: 'Warna' },
      { key: 'price', header: 'Harga', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'vu1', vin: 'MHKM1BA3JKJ001122', product: 'Toyota Avanza 1.5 G', year: 2023, color: 'Putih', price: 245000000, status: 'ACTIVE' },
      { id: 'vu2', vin: 'MHKM1BA3JKJ003344', product: 'Mitsubishi Xpander Ultimate', year: 2024, color: 'Hitam', price: 285000000, status: 'RESERVED' },
      { id: 'vu3', vin: 'MHKM1BA3JKJ005566', product: 'Honda BR-V E CVT', year: 2024, color: 'Silver', price: 315000000, status: 'SOLD' },
    ],
  },
  {
    path: '/showroom/test-drives',
    title: 'Test Drives',
    description: 'Jadwal dan riwayat test drive.',
    icon: 'testdrive',
    resource: 'showroom.test_drive',
    createLabel: 'Jadwalkan Test Drive',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'unit', header: 'Unit' },
      { key: 'sales', header: 'Sales' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'td1', number: 'TD-0009', date: '2026-07-12', customer: 'Dedi Kurniawan', unit: 'Toyota Avanza 1.5 G', sales: 'Andi', status: 'PENDING' },
      { id: 'td2', number: 'TD-0008', date: '2026-07-08', customer: 'Maya Putri', unit: 'Honda BR-V E CVT', sales: 'Rina', status: 'ACTIVE' },
    ],
  },
  {
    path: '/showroom/reservations',
    title: 'Reservations',
    description: 'Pemesanan unit oleh pelanggan.',
    icon: 'reservation',
    resource: 'showroom.reservation',
    createLabel: 'Buat Reservasi',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'unit', header: 'Unit' },
      { key: 'deposit', header: 'DP', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'rs1', number: 'RSV-0005', date: '2026-07-07', customer: 'PT Maju Jaya', unit: 'Mitsubishi Xpander Ultimate', deposit: 10000000, status: 'ACTIVE' },
    ],
  },
  {
    path: '/showroom/deliveries',
    title: 'Deliveries',
    description: 'Serah terima kendaraan ke pelanggan.',
    icon: 'delivery',
    resource: 'showroom.delivery',
    createLabel: 'Jadwalkan Serah Terima',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'unit', header: 'Unit' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'dl1', number: 'DLV-0003', date: '2026-07-14', customer: 'Budi Santoso', unit: 'Honda BR-V E CVT', status: 'PENDING' },
    ],
  },
  {
    path: '/showroom/trade-ins',
    title: 'Trade-ins',
    description: 'Tukar tambah: inspeksi, appraisal, penawaran, akuisisi.',
    icon: 'tradein',
    resource: 'showroom.trade_in',
    createLabel: 'Buat Trade-in',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'vehicle', header: 'Kendaraan' },
      { key: 'appraisal', header: 'Appraisal', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ti1', number: 'TI-0004', date: '2026-07-06', customer: 'Siti Rahma', vehicle: 'Toyota Agya 2019', appraisal: 95000000, status: 'PENDING' },
    ],
  },
  {
    path: '/showroom/leasing',
    title: 'Leasing',
    description: 'Perusahaan leasing, simulasi, dan pengajuan pembiayaan.',
    icon: 'leasing',
    resource: 'showroom.leasing',
    createLabel: 'Buat Pengajuan',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'company', header: 'Leasing' },
      { key: 'amount', header: 'Plafon', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ls1', number: 'LSA-0011', date: '2026-07-09', customer: 'Dedi Kurniawan', company: 'Adira Finance', amount: 200000000, status: 'PENDING' },
    ],
  },

  // ── Finance ────────────────────────────────────────────────────────────────
  {
    path: '/finance/accounts',
    title: 'Chart of Accounts',
    description: 'Daftar akun buku besar.',
    icon: 'account',
    resource: 'finance.account',
    createLabel: 'Tambah Akun',
    columns: [
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'name', header: 'Nama Akun', kind: 'bold' },
      { key: 'type', header: 'Tipe' },
      { key: 'balance', header: 'Saldo', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ac1', code: '1-1000', name: 'Kas', type: 'Aset', balance: 152000000, status: 'ACTIVE' },
      { id: 'ac2', code: '1-1100', name: 'Bank BCA', type: 'Aset', balance: 890000000, status: 'ACTIVE' },
      { id: 'ac3', code: '2-1000', name: 'Utang Usaha', type: 'Liabilitas', balance: 735000000, status: 'ACTIVE' },
    ],
  },
  {
    path: '/finance/fiscal-periods',
    title: 'Fiscal Periods',
    description: 'Periode akuntansi dan status tutup buku.',
    icon: 'fiscalperiod',
    resource: 'finance.fiscal_period',
    createLabel: 'Tambah Periode',
    columns: [
      { key: 'name', header: 'Periode', kind: 'bold' },
      { key: 'startDate', header: 'Mulai', kind: 'date' },
      { key: 'endDate', header: 'Selesai', kind: 'date' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'fp1', name: 'Juli 2026', startDate: '2026-07-01', endDate: '2026-07-31', status: 'ACTIVE' },
      { id: 'fp2', name: 'Juni 2026', startDate: '2026-06-01', endDate: '2026-06-30', status: 'INACTIVE' },
    ],
  },
  {
    path: '/finance/payments',
    title: 'Payments',
    description: 'Penerimaan, pembayaran, alokasi, dan refund.',
    icon: 'payment',
    resource: 'finance.payment',
    createLabel: 'Catat Pembayaran',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'type', header: 'Tipe' },
      { key: 'party', header: 'Pihak', kind: 'bold' },
      { key: 'amount', header: 'Nilai', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'pm1', number: 'RCP-0014', date: '2026-07-11', type: 'Penerimaan', party: 'Budi Santoso', amount: 250000000, status: 'ACTIVE' },
      { id: 'pm2', number: 'DSB-0009', date: '2026-07-10', type: 'Pembayaran', party: 'PT Astra Distribusi', amount: 300000000, status: 'PENDING' },
    ],
  },
  {
    path: '/finance/journals',
    title: 'Journals',
    description: 'Jurnal umum dan posting-nya.',
    icon: 'journal',
    resource: 'finance.journal',
    createLabel: 'Buat Jurnal',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'description', header: 'Keterangan', kind: 'bold' },
      { key: 'debit', header: 'Debit', kind: 'money', align: 'right' },
      { key: 'credit', header: 'Kredit', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'jr1', number: 'JV-0102', date: '2026-07-11', description: 'Penjualan unit BR-V', debit: 315000000, credit: 315000000, status: 'ACTIVE' },
    ],
  },
  {
    path: '/finance/receivables',
    title: 'Receivables',
    description: 'Piutang pelanggan dan jatuh temponya.',
    icon: 'receivable',
    resource: 'finance.receivable',
    columns: [
      { key: 'invoice', header: 'Faktur', kind: 'mono' },
      { key: 'customer', header: 'Customer', kind: 'bold' },
      { key: 'amount', header: 'Nilai', kind: 'money', align: 'right' },
      { key: 'outstanding', header: 'Sisa', kind: 'money', align: 'right' },
      { key: 'dueDate', header: 'Jatuh Tempo', kind: 'date' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ar1', invoice: 'INV-0027', customer: 'Budi Santoso', amount: 315000000, outstanding: 65000000, dueDate: '2026-07-25', status: 'PENDING' },
    ],
  },
  {
    path: '/finance/payables',
    title: 'Payables',
    description: 'Utang ke supplier dan jatuh temponya.',
    icon: 'payable',
    resource: 'finance.payable',
    columns: [
      { key: 'invoice', header: 'Faktur', kind: 'mono' },
      { key: 'supplier', header: 'Supplier', kind: 'bold' },
      { key: 'amount', header: 'Nilai', kind: 'money', align: 'right' },
      { key: 'outstanding', header: 'Sisa', kind: 'money', align: 'right' },
      { key: 'dueDate', header: 'Jatuh Tempo', kind: 'date' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ap1', invoice: 'PINV-0031', supplier: 'PT Astra Distribusi', amount: 735000000, outstanding: 735000000, dueDate: '2026-08-09', status: 'PENDING' },
    ],
  },
  {
    path: '/finance/cash-bank',
    title: 'Cash & Bank',
    description: 'Posisi kas dan rekening bank.',
    icon: 'cashbank',
    resource: 'finance.cash_bank',
    createLabel: 'Tambah Transaksi',
    columns: [
      { key: 'account', header: 'Akun', kind: 'bold' },
      { key: 'bank', header: 'Bank' },
      { key: 'number', header: 'No. Rekening', kind: 'mono' },
      { key: 'balance', header: 'Saldo', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'cb1', account: 'Kas Besar', bank: '—', number: '—', balance: 152000000, status: 'ACTIVE' },
      { id: 'cb2', account: 'Bank Operasional', bank: 'BCA', number: '123-456-7890', balance: 890000000, status: 'ACTIVE' },
    ],
  },
  {
    path: '/finance/expenses',
    title: 'Expenses',
    description: 'Pengeluaran operasional showroom.',
    icon: 'expense',
    resource: 'finance.expense',
    createLabel: 'Catat Pengeluaran',
    columns: [
      { key: 'number', header: 'Nomor', kind: 'mono' },
      { key: 'date', header: 'Tanggal', kind: 'date' },
      { key: 'category', header: 'Kategori' },
      { key: 'description', header: 'Keterangan', kind: 'muted' },
      { key: 'amount', header: 'Nilai', kind: 'money', align: 'right' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'ex1', number: 'EXP-0056', date: '2026-07-10', category: 'Operasional', description: 'Listrik showroom', amount: 4500000, status: 'ACTIVE' },
    ],
  },
  {
    path: '/finance/reports',
    title: 'Finance Reports',
    description: 'Laporan keuangan: neraca, laba rugi, arus kas, aging.',
    icon: 'report',
    resource: 'finance.report',
    columns: [
      { key: 'name', header: 'Laporan', kind: 'bold' },
      { key: 'period', header: 'Periode' },
      { key: 'updatedAt', header: 'Diperbarui', kind: 'date' },
    ],
    rows: [
      { id: 'rp1', name: 'General Ledger', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'rp2', name: 'Trial Balance', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'rp3', name: 'Profit & Loss', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'rp4', name: 'Balance Sheet', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'rp5', name: 'Cash Flow', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'rp6', name: 'Receivable Aging', period: 'Juli 2026', updatedAt: '2026-07-12' },
      { id: 'rp7', name: 'Payable Aging', period: 'Juli 2026', updatedAt: '2026-07-12' },
    ],
  },

  // ── Settings (selain Users/Roles/General yang punya halaman sendiri) ────────
  {
    path: '/settings/numbering',
    title: 'Numbering',
    description: 'Format penomoran dokumen per modul.',
    icon: 'numbering',
    resource: 'tenant.numbering',
    createLabel: 'Tambah Format',
    columns: [
      { key: 'module', header: 'Modul', kind: 'bold' },
      { key: 'prefix', header: 'Prefix', kind: 'mono' },
      { key: 'format', header: 'Format', kind: 'mono' },
      { key: 'next', header: 'Berikutnya', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'nb1', module: 'Sales Order', prefix: 'SO', format: 'SO-{0000}', next: 32, status: 'ACTIVE' },
      { id: 'nb2', module: 'Purchase Order', prefix: 'PO', format: 'PO-{0000}', next: 45, status: 'ACTIVE' },
    ],
  },
  {
    path: '/settings/approvals',
    title: 'Approvals',
    description: 'Alur persetujuan dokumen.',
    icon: 'approval',
    resource: 'tenant.approval',
    createLabel: 'Tambah Alur',
    columns: [
      { key: 'module', header: 'Modul', kind: 'bold' },
      { key: 'condition', header: 'Kondisi' },
      { key: 'approver', header: 'Penyetuju' },
      { key: 'levels', header: 'Level', kind: 'number', align: 'center' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'apv1', module: 'Purchase Order', condition: 'Total > 500 juta', approver: 'Owner', levels: 1, status: 'ACTIVE' },
      { id: 'apv2', module: 'Quotation', condition: 'Diskon > 5%', approver: 'Sales Manager', levels: 1, status: 'ACTIVE' },
    ],
  },
  {
    path: '/settings/modules',
    title: 'Module Settings',
    description: 'Capability tenant — read-only, diaktifkan dari Platform.',
    icon: 'module',
    resource: 'tenant.module_settings',
    columns: [
      { key: 'name', header: 'Modul', kind: 'bold' },
      { key: 'code', header: 'Kode', kind: 'mono' },
      { key: 'status', header: 'Status', kind: 'status' },
    ],
    rows: [
      { id: 'cp1', name: 'Catalogue', code: 'catalogue', status: 'ACTIVE' },
      { id: 'cp2', name: 'Inventory', code: 'inventory', status: 'ACTIVE' },
      { id: 'cp3', name: 'Purchasing', code: 'purchasing', status: 'ACTIVE' },
      { id: 'cp4', name: 'Sales', code: 'sales', status: 'ACTIVE' },
      { id: 'cp5', name: 'Showroom', code: 'showroom', status: 'ACTIVE' },
      { id: 'cp6', name: 'Finance', code: 'finance', status: 'ACTIVE' },
      { id: 'cp7', name: 'Leasing', code: 'leasing', status: 'INACTIVE' },
    ],
  },
];

const BY_PATH = new Map(MODULES.map((m) => [m.path, m]));

export const getModule = (path: string) => BY_PATH.get(path);
